version: "3"

services:
  nodeosd:
    image: registry.cn-shenzhen.aliyuncs.com/eosmore/eosio:${EOSIO_VERSION}
    command: "/opt/eosio/bin/nodeosd.sh --max-transaction-time 200 --contracts-console --genesis-json /opt/eosio/bin/data-dir/genesis.json -e"
    working_dir:
      /opt/eosio/bin/
    ports:
      - ${HTTP_PORT}:8888
      - ${P2P_PORT}:9876
    expose:
      - "8888"
    volumes:
      - ./data-dir:/opt/eosio/bin/data-dir
      - ${BLOCK_DATA_PATH}:/root/.local/share/eosio/nodeos/data
  keosd:
    image: registry.cn-shenzhen.aliyuncs.com/eosmore/eosio:${EOSIO_VERSION}
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/wallet-dir --http-server-address=127.0.0.1:8900
    working_dir:
      /opt/eosio/bin/
    expose:
      - "8900" 
    links:
      - nodeosd   
    volumes:
      - ./data-dir:/opt/eosio/bin/data-dir
      - ${WALLET_PATH}:/opt/eosio/bin/wallet-dir