version: "3"

services:
  mongo:
    image: bitnami/mongodb:3.7
    volumes:
      - ${MONGO_DATA_PATH}:/bitnami/mongodb
    environment:
      MONGODB_USERNAME: eos
      MONGODB_PASSWORD: secret
      MONGODB_ROOT_PASSWORD: secret
      MONGODB_DATABASE: eos  
    ports:
      - "27017:27017"
  nodeosd:
    image: noprom/eos:mongo
    command: "/opt/eosio/bin/nodeos --data-dir=/data --config-dir=/etc/nodeos --genesis-json /etc/nodeos/genesis.json --mongodb-wipe --mongodb-uri mongodb://eos:secret@mongo:27017/eos"
    working_dir:
      /opt/eosio/bin/
    ports:
      - ${HTTP_PORT}:8888
      - ${P2P_PORT}:9876
    expose:
      - "8888"
    volumes:
      - ./config:/etc/nodeos
      - ${BLOCK_DATA_PATH}:/data