version: "2"

services:
  nodeosd:
    image: eosio/eos:${EOSIO_VERSION}
    command: /opt/eosio/bin/nodeosd.sh
    working_dir:
      /opt/eosio/bin/
    ports:
      - ${HTTP_PORT}:8888
      - ${P2P_PORT}:9876
    expose:
      - "8888"
    volumes:
      - ./data-dir:/opt/eosio/bin/data-dir
      - ${BLOCK_DATA_PATH}:/root/.local/share/eosio/nodeos/data
    networks: 
      - frontend
      - backend  
  keosd:
    image: eosio/eos:${EOSIO_VERSION}
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir
    volumes:
      - ./data-dir:/opt/eosio/bin/data-dir
    networks:
      - backend  
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"  